# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Flieh Files
email: ruedelaflieh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is intended for self use. I will document all the new technologies and techniques that I'm working on. I'm hoping this will allow me to use Google to dig up answers to questions that I've already found but that I've forgotten. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http:/flieh.surge.sh" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SeaninFrance
github_username:  flieh

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
