---
title: The Flieh Files
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: ruedelaflieh@gmail.com
description: "This blog is intended for self use. I will document all the new technologies
  and techniques that I'm working on. I'm hoping this will allow me to use Google
  to dig up answers to questions that I've already found but that I've forgotten.
  \n"
baseurl: ''
url: http:/flieh.surge.sh
twitter_username: SeaninFrance
github_username: flieh
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
